# Built with Jekyll 3.2.0

# Setup
title:               Beyond Survival
tagline:             'a defence of Montreal Chinatown'
description:         ''
url:                 'http://briannacheng.github.io'
baseurl:             '/'

# About/contact
author:
  name:              Brianna Cheng # AND CHRIS KROFCHAK kinda
  url:               https://building21.ca/blue-interns-winter-2021
  email:             brianna.cheng@mail.mcgill.ca

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


